//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStep.Extensions.LocalExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalExtensionResolverMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalExtensionResolverMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoStep.Extensions.LocalExtensions.LocalExtensionResolverMessages", typeof(LocalExtensionResolverMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of more of the configured local projects could not be built, so we cannot continue..
        /// </summary>
        internal static string BuildFailure {
            get {
                return ResourceManager.GetString("BuildFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Local Projects..
        /// </summary>
        internal static string BuildingProjects {
            get {
                return ResourceManager.GetString("BuildingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured extension folder &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string ExtensionFolderDoesNotExist {
            get {
                return ResourceManager.GetString("ExtensionFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured extension folder &apos;{0}&apos; does not contain a .NET project file..
        /// </summary>
        internal static string FolderDoesNotHaveAProjectFile {
            get {
                return ResourceManager.GetString("FolderDoesNotHaveAProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including .NET Project File &apos;{0}&apos; as a local extension..
        /// </summary>
        internal static string IncludingProjectFile {
            get {
                return ResourceManager.GetString("IncludingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder provided for configured local extension..
        /// </summary>
        internal static string NoFolderProvided {
            get {
                return ResourceManager.GetString("NoFolderProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an installed dotnet SDK on this machine. Using folder extensions with code requires the dotnet SDK, which can be downloaded from https://dotnet.microsoft.com/download/..
        /// </summary>
        internal static string NoSDK {
            get {
                return ResourceManager.GetString("NoSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Projects Built Successfully..
        /// </summary>
        internal static string ProjectsBuiltOk {
            get {
                return ResourceManager.GetString("ProjectsBuiltOk", resourceCulture);
            }
        }
    }
}
